inreru/config/routes.rb
Inreru::Application.routes.draw do
  resources :trials

  devise_for :users
  resources :tokens, only: [:create, :destroy]
  resources :measurements, only: [:create]

end

inreru/app/models/measurement.rb
class Measurement < ActiveRecord::Base
  attr_accessible :date, :grade, :trial_id
  belongs_to :trial
end

inreru/app/models/trial.rb
class Trial < ActiveRecord::Base
  
  belongs_to :user
  has_many :measurements
  accepts_nested_attributes_for :measurements
  attr_accessible :date, :name, :user_id, :measurements_attributes
end

inreru/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :token_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :trial_attributes
  # attr_accessible :title, :body
  has_many :trials
  accepts_nested_attributes_for :trials
end

inreru/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

inreru/app/controllers/measurements_controller.rb
class MeasurementsController < ApplicationController
 before_filter :authenticate_user!
def create
    @measurement = Measurement.new(params[:measurement])

    respond_to do |format|
      if @measurement.save
       render status: 200, json: {message: "Success"}
      else
        render status: 401, json: {message: "Failure"}
      end
    end
  end

end

inreru/app/controllers/tokens_controller.rb
class TokensController  < ApplicationController
    skip_before_filter :verify_authenticity_token
    respond_to :json
    def create
      email = params[:email]
      password = params[:password]
      if request.format != :json
        render :status=>406, :json=>{:message=>"The request must be json"}
        return
       end
 
    if email.nil? or password.nil?
       render :status=>400,
              :json=>{:message=>"The request must contain the user email and password."}
       return
    end
 
    @user=User.find_by_email(email.downcase)
 
    if @user.nil?
      logger.info("User #{email} failed signin, user cannot be found.")
      render :status=>401, :json=>{:message=>"Invalid email or passoword."}
      return
    end
 
    # http://rdoc.info/github/plataformatec/devise/master/Devise/Models/TokenAuthenticatable
    @user.ensure_authentication_token!
 
    if not @user.valid_password?(password)
      logger.info("User #{email} failed signin, password \"#{password}\" is invalid")
      render :status=>401, :json=>{:message=>"Invalid email or password."}
    else
      render :status=>200, :json=>{:token=>@user.authentication_token, :user_id=>@user.id}
    end
  end
 
  def destroy
    @user=User.find_by_authentication_token(params[:id])
    if @user.nil?
      logger.info("Token not found.")
      render :status=>404, :json=>{:message=>"Invalid token."}
    else
      @user.reset_authentication_token!
      render :status=>200, :json=>{:token=>params[:id]}
    end
  end
 
end

inreru/app/controllers/trials_controller.rb
class TrialsController < ApplicationController
  before_filter :authenticate_user!
  # GET /trials
  # GET /trials.json
  def index
    @trials = Trial.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @trials }
    end
  end

  # GET /trials/1
  # GET /trials/1.json
  def show
    @trial = Trial.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @trial }
    end
  end

  # GET /trials/new
  # GET /trials/new.json
  def new
    @trial = Trial.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @trial }
    end
  end

  # GET /trials/1/edit
  def edit
    @trial = Trial.find(params[:id])
  end

  # POST /trials
  # POST /trials.json
  def create
    @trial = Trial.new(params[:trial])

    respond_to do |format|
      if @trial.save
        format.html { redirect_to @trial, notice: 'Trial was successfully created.' }
        format.json { render json: @trial, status: :created, location: @trial, id: @trial.id }
      else
        format.html { render action: "new" }
        format.json { render json: @trial.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /trials/1
  # PUT /trials/1.json
  def update
    @trial = Trial.find(params[:id])

    respond_to do |format|
      if @trial.update_attributes(params[:trial])
        format.html { redirect_to @trial, notice: 'Trial was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @trial.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trials/1
  # DELETE /trials/1.json
  def destroy
    @trial = Trial.find(params[:id])
    @trial.destroy

    respond_to do |format|
      format.html { redirect_to trials_url }
      format.json { head :no_content }
    end
  end
end

inreru/app/helpers/application_helper.rb
module ApplicationHelper
end

inreru/app/helpers/trials_helper.rb
module TrialsHelper
end

inreru/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Inreru</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

inreru/app/views/trials/_form.html.erb
<%= form_for(@trial) do |f| %>
  <% if @trial.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trial.errors.count, "error") %> prohibited this trial from being saved:</h2>

      <ul>
      <% @trial.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br />
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

inreru/app/views/trials/edit.html.erb
<h1>Editing trial</h1>

<%= render 'form' %>

<%= link_to 'Show', @trial %> |
<%= link_to 'Back', trials_path %>

inreru/app/views/trials/index.html.erb
<h1>Listing trials</h1>

<table>
  <tr>
    <th>Date</th>
    <th>User</th>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @trials.each do |trial| %>
  <tr>
    <td><%= trial.date %></td>
    <td><%= trial.user_id %></td>
    <td><%= trial.name %></td>
    <td><%= link_to 'Show', trial %></td>
    <td><%= link_to 'Edit', edit_trial_path(trial) %></td>
    <td><%= link_to 'Destroy', trial, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Trial', new_trial_path %>

inreru/app/views/trials/new.html.erb
<h1>New trial</h1>

<%= render 'form' %>

<%= link_to 'Back', trials_path %>

inreru/app/views/trials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Date:</b>
  <%= @trial.date %>
</p>

<p>
  <b>User:</b>
  <%= @trial.user_id %>
</p>

<p>
  <b>Name:</b>
  <%= @trial.name %>
</p>

	<% @trial.measurements.each do |p| %>
		<p><%= p.grade %></p>
		<%end%>
<%= link_to 'Edit', edit_trial_path(@trial) %> |
<%= link_to 'Back', trials_path %>